federation_version: =2.5.3
subgraphs:
  locations:
    routing_url: http://127.0.0.1:4001
    schema:
      subgraph_url: http://127.0.0.1:4001
  reviews:
    routing_url: http://127.0.0.1:4002
    schema:
      subgraph_url: http://127.0.0.1:4002
  users:
    routing_url: http://127.0.0.1:8080
    schema:
      subgraph_url: http://127.0.0.1:8080
      # introspection_headers:
      #   Authorization: Bearer ${env.PEOPLE_AUTH_TOKEN}
